# Generated by Django 3.0.8 on 2020-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_auto_20200711_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='intensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='maximeter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='power_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='reactive_energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='reactive_power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
