# Generated by Django 3.0.8 on 2020-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_auto_20200711_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='reactive_energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='reactive_power',
            field=models.FloatField(default=0.0),
        ),
    ]
