# Generated by Django 3.0.8 on 2020-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_auto_20200711_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='reactive_energy',
            field=models.FloatField(default=1.0),
        ),
    ]
